#  Build & Run FHIR Publisher, and push output to gh-pages

langauge: java
jdk:
  - oraclejdk7
script: ./build.sh
notifications:
  email:
    - fhir-svn-travis@dilute.net
    - grahame@healthintersections.com.au
    - e.kramer@furore.com
